src/main/java/axoloti/Patch.java
ensure CC and other midi messages are only sent to correct subpatch in multichannel mode
=> fix poly multichannel for cc/channel pressure

firmware/midi.h, objects/midi/mpe/keyb mpe.axo, src/main/java/axoloti/Patch.java, src/main/java/axoloti/SubPatchMode.java, src/main/java/axoloti/attribute/AttributeInstanceObjRef.java, src/main/java/axoloti/dialogs/PatchSettingsFrame.form, src/main/java/axoloti/dialogs/PatchSettingsFrame.java
Ive created a new polyphonic expression sub patch mode, which is similar to polymultichannel but contains the MPE specifics. also it included a new axoloti object (keyb mpe) which can be used for these 'standard' expressions.
(I'm going to now do some patches which illustrate this with the soundplane, which Ive been using for testing)
=> Changes to support the new midi polyphonic expression spec (MPE)

src/main/java/axoloti/dialogs/AxoObjectEditor.form, src/main/java/axoloti/dialogs/AxoObjectEditor.java, src/main/java/axoloti/inlets/Inlet.java, src/main/java/axoloti/outlets/Outlet.java, src/main/java/axoloti/outlets/OutletBool32.java, src/main/java/axoloti/outlets/OutletCharPtr32.java, src/main/java/axoloti/outlets/OutletFrac32.java, src/main/java/axoloti/outlets/OutletFrac32Buffer.java, src/main/java/axoloti/outlets/OutletInt32.java
update object editor so we can see inlets/outlets/params/attributes.
=> add basic view capability to params/atrributes/inlets/outlets on editor

platform_osx/build.sh
the gcc/chiobios are quite big downloads, so tell users whats going on :)
=> curl doesnt show what its downloading so tell user

objects/midi/mpe/keyb mpe.axo, src/main/java/axoloti/Patch.java
tested MPE working fine over core midi OS X  to oxalate core.
updated MPE object, and found a couple more minor changes for patch.java regarding poly objects
=> update mpe to new axo inlets, GUI: fix patch outlets for poly patches

firmware/midi.h, src/main/java/axoloti/Patch.java
(also update comment in midi.h)
=> add usb device as midi filter option on subpatches

objects/midi/mpe/keyb mpe.axh, objects/midi/mpe/keyb mpe.axo, src/main/java/generatedobjects/Midi.java
help file shows using MPE as a simple voice
=> MPE object added to generator, new help file

nbproject/project.properties, objects/midi/ctrl/index.html, objects/midi/ctrl/mpe.axh, objects/midi/ctrl/mpe.axo, src/main/java/generatedobjects/Midi.java
will be useful for things like Push support, or other controllers which have specific CC mappings
(note: controllers can have both input and output mappings, so best not to classify as in or out)
also, update Netbeans project, remove jssc.jar
=> create new directory for supporting specific midi controllers

.gitignore, build.xml, platform_win/path.bat, platform_win/test_env.bat, src/main/java/axoloti/dialogs/AboutFrame.form, src/main/java/axoloti/dialogs/AboutFrame.java, src/main/java/axoloti/dialogs/AxoObjectEditor.form, src/main/java/axoloti/dialogs/AxoObjectEditor.java
note: version number on app bundles is fixed to 1.0, this appears to be a bug in javafx
=> add git version, fixes #115, minor window script changes

objects/harmony/note quantizer.axo, src/main/java/axoloti/object/AxoObjectInstance.java, src/main/java/generatedobjects/Harmony.java
axoobject instance add attr_legal_name, reqd for param index building
=> obj:note quantizer, allow scale to be set from midi 

platform_linux/build.sh
I just received the board and installed the software on Archlinux. Thank you so much!
The software installs and works fine with my changes to the `platform_linux` build script.
Hope I did not destroy anything for debian or ubuntu users. :-)
=> Support Archlinux distribution

objects/patch/outlet string.axo, src/main/java/axoloti/Patch.java, src/main/java/generatedobjects/Patch.java
String Outlet for subpatches with required additions to patcher code.
=> Added String Outlet object and patcher adjustments

objects/patch/inlet string.axo, objects/patch/outlet string.axo, src/main/java/axoloti/Patch.java, src/main/java/generatedobjects/Patch.java
implemented polyphonic subobject support, added string inlet, optimized
code by placing functions into patch.java instead of .axo
=> Inlet and Outlet String improvements

firmware/compile_firmware_linux.sh, firmware/compile_firmware_osx.sh, firmware/compile_firmware_win.bat, firmware/mcuconf.h, firmware/mounter/.gitignore, firmware/mounter/Makefile, firmware/mounter/STM32F407xG standalone.ld, firmware/mounter/STM32F407xG.ld, firmware/mounter/board.c, firmware/mounter/board.mk, firmware/mounter/chconf.h, firmware/mounter/halconf.h, firmware/mounter/main.c, firmware/mounter/mass_storage/Readme.md, firmware/mounter/mass_storage/usb_msd.c, firmware/mounter/mass_storage/usb_msd.h, src/main/java/axoloti/MainFrame.form, src/main/java/axoloti/MainFrame.java, src/main/java/axoloti/dialogs/USBPortSelectionDlg.java, src/main/java/axoloti/usb/Usb.java
Tested on Windows 7, untested on MacOS and Linux. Comments welcome!
=> Sdcard mounter

src/main/java/axoloti/utils/AxoGitLibrary.java
=> UL: handle git local/remote branches correctly

nbproject/jnlp-impl.xml, nbproject/jnlp-impl_backup.xml, src/main/java/axoloti/object/AxoObjects.java, src/main/java/axoloti/objecteditor/AddToLibraryDlg.form, src/main/java/axoloti/objecteditor/AddToLibraryDlg.java, src/main/java/axoloti/objecteditor/AxoObjectEditor.form, src/main/java/axoloti/objecteditor/AxoObjectEditor.java
- fix issues with object naming (memory model has id as cat/id serialised form is without cat!)
- correctly updated all fields
- add close() when modified warning
- tell object in patcher when modified
=> obj editor improvments

platform_linux/build.sh
I left my Axoloti in the box for three months because I was so scared of tackling the build system.  You can see, it didn't end up being very hard at all.
Thanks for Axoloti!
=> Add gentoo support

src/main/java/axoloti/ObjectSearchFrame.form, src/main/java/axoloti/ObjectSearchFrame.java
@JohannesTaelman 
Here's a patch that causes the object previews in the object chooser to be displayed at the current patch zoom level.
=> GUI: object preview zoom

src/main/java/axoloti/PatchGUI.java
This is per Mark's request. I think it looks better too.
=> GUI: float dragged objects above wires

src/main/java/axoloti/Net.java, src/main/java/axoloti/NetDragging.java, src/main/java/axoloti/Patch.java, src/main/java/axoloti/PatchFrame.java, src/main/java/axoloti/PatchGUI.java, src/main/java/axoloti/attribute/AttributeInstanceSDFile.java, src/main/java/axoloti/dialogs/PreferencesFrame.java, src/main/java/axoloti/iolet/IoletAbstract.java, src/main/java/axoloti/menus/FileMenu.java, src/main/java/axoloti/object/AxoObjectInstance.java, src/main/java/axoloti/object/AxoObjectInstanceAbstract.java, src/main/java/components/control/ACtrlComponent.java, src/main/java/components/control/DialComponent.java, src/main/java/components/control/NumberBoxComponent.java
The fixes the issues that Mark was running into with undoing deletions. There is still a slight net repaint issue that existed before this patch that I'm still tracking down.
=> GUI: fix deletion undo

firmware/patch.h
=> adding flag STARTFAILED to patch.h

src/main/java/axoloti/PatchGUI.java, src/main/java/axoloti/ZoomUI.java, src/main/java/axoloti/iolet/IoletAbstract.java
ZoomUI can still be made a bit more compact than this, but this brings it back online with the new drag and drop approach.
=> GUI: zoomui back online

platform_linux/build.sh
This adds support for fedora in build.sh
=> Added fedora support

src/main/java/components/control/DialComponent.java
I hope this is sufficient - I was unsure if alt was also necessary. isShortcutKey seems to only be in JavaFX.
=> GUI: fix paste by ignoring appropriately modified alphanumeric events.

src/main/java/axoloti/object/AxoObjects.java
An example of a patch that exercises this feature is axoloti-factory/patches/tutorials/15_waveshaper.axp.
=> Fix cwd object subpatch loading

platform_linux/build.sh
Adds build support for [manjaro linux](https://manjaro.org/).
=> Add support for manjaro linux

src/main/java/axoloti/swingui/objecteditor/AxoObjectEditor.form, src/main/java/axoloti/swingui/objecteditor/AxoObjectEditor.java
a bit bigger window so all tabs fit and only show the description scrollbar when necessary.
=> GUI: tweak some object editor dimensions

platform_linux/add_udev_rules.sh, platform_linux/build.sh
Ask whether to install packages as it doesn't check whether they are already installed.
=> Improve linux build script
