axoloti/axoloti

src/main/java/axoloti/ObjectSearchFrame.java, src/main/java/axoloti/TextEditor.java, src/main/java/axoloti/dialogs/CodeDialog.java, src/main/java/axoloti/dialogs/PatchSettingsFrame.java, src/main/java/axoloti/dialogs/PreferencesFrame.java, src/main/java/axoloti/dialogs/SerialPortSelectionDlg.java, src/main/java/axoloti/object/AxoObjects.java, src/main/java/components/PresetPanel.java
- search dialog showed empty nodes (which look liked objects), now only shows directories which (at some level) contains axo files.
- java fixed compiler warnings when compiling with ant  (missing param tags)
=> remove empty leaf nodes on search dialog, fix compiler (java) compiler warnings

objects/brainwave/read.axo, objects/delay/write sdram.axo, objects/spectral/rfft 128.axo, objects/wave/longdelay.axo, src/main/java/generatedobjects/Distortion.java, src/main/java/generatedobjects/Filter.java, src/main/java/generatedobjects/LTC.java, src/main/java/generatedobjects/Spectral.java, src/main/java/generatedobjects/Wave.java, src/main/java/generatedobjects/brainwave.java
Ive commented out some objects in generated, as the axo objects have not been checked in.
(so Ive assumed they are not ready for release)
Ive marked with //UNRELEASED, these are:
objects/dist/rectifierlab.axo
objects/filter/lp svf drive.axo
objects/ltc/fsync coded.axo
objects/ltc/fsync.axo
objects/wave/play3 fn stereo 32.axo
objects/wave/record.axo
if you think that some of these should be released, then un-comment and check axo in.
(I think we should ensure axo's and generated are always in sync, just so we know its always safe to regenerate objects)
=> fix rfft&brainwave. ensure generated and axo are in sync

Axoloti.command, Axoloti.sh, build.xml, firmware/Makefile, patch/Makefile, platform_linux/compile_firmware.sh, platform_linux/compile_patch.sh, platform_linux/upload_fw_dfu.sh, platform_osx/compile_firmware.sh, platform_osx/compile_patch.sh, platform_osx/upload_fw_dfu.sh, src/main/java/axoloti/Axoloti.java, src/main/java/axoloti/Patch.java, src/main/java/qcmds/QCmdCompileFirmware.java, src/main/java/qcmds/QCmdFlashDFU.java, src/main/java/qcmds/QCmdShellTask.java, src/main/java/qcmds/QCmdUploadFWSDRam.java, src/main/java/qcmds/QCmdUploadPatch.java, src/main/java/qcmds/QCmdWriteFile.java
- new build.runtime target for mac and linux to build a runtime image, linux gets a tar file, mac gets a DMG
- new firmware environment var used to pickup firmware, defaults to release area, but can be overridden by user to build from somewhere else (axoloti home/firmware is good)
- axoloti_home replaces axoloti_build
to do
- store preferences in axoloti_home/preferences.xml
- create 'default firmware upload menu'
- test with an application bundle.
- compile/upload scripts for windows (in platform_win), copy pattern used by linux/osx
- build.runtime for windows... again copy linux/osx model
NOTE: build.xml deliberately uses native commands it HAS to to ensure file permissions are left intact, all ANT tasks will remove execute permissions. (and they are a pain to add back!)
=> installation improvements , issue #94

build.xml
so user can copy firmware dir safely
=> bundle:only bundle firmwares bin/elf, fixes and closes #185

platform_linux/build.sh
The archlinux build fails because of some minor errors in the buid script:
* lsb-release contains the string 'Arch' but the build script expects 'Archlinux'
* the package 'apache-ant' is required but is missing in the package installation
=> Fix archlinux build

firmware/ramlink.ld
... so that it is the actual patch_init() function that is called
when PATCHMALLOC is called, and not the constructors and destructors
init_array and fini_array pointers, respectively, which just contain
pointers and no code.
=> Keep text segment at start of binary

platform_linux/build.sh
build.sh will die on more recent versions of Ubuntu when we attempt to install lib32bz2-1.0. This package now comes in a multi-arch flavor, so what we want is libbz2-1.0:i386. This patch simply attempts to use the old name first and then the new one if needed.
=> Improve lib bz2 dependency installation

src/main/java/axoloti/menus/FileMenu.java
Currently, opening a patch from the MainFrame's menu properly brings it to the front. Opening a patch from an existing open PatchFrame results in the new patch appearing behind the patch that the open was invoked from. This is happening indirectly as a result of the hardcoded reference to MainFrame in FileMenu which gets reused in PatchFrame. We simply grab a reference to the parent frame and use it when creating the open dialog and we get the correct toFront behavior. The open dialog is also then positioned relative to the invoking frame.
=> Fix patch opening toFront behavior

src/main/java/axoloti/Patch.java, src/main/java/axoloti/PatchFrame.form, src/main/java/axoloti/PatchFrame.java, src/main/java/axoloti/PatchGUI.java, src/main/java/axoloti/object/AxoObjectInstanceAbstract.java
@JohannesTaelman 
I was able to find a way to complete my previous undo/redo attempt. The approach is fairly non-invasive and captures net, object and parameter changes in what I think is a pretty reasonable way. Its notion of what constitutes an undoable action mirrors how setDirty() currently works. Pasting or moving a group of objects for example is a single undoable action. I'm currently disallowing undo/redo in live mode, but parameter edits are still captured so you can step back through them when you return to edit mode. This is something that can probably be worked around later, but this gets us most of the way there I think.
The UI is the usual thing: undo and redo items in the edit menu with Ctrl-Z and Shift-Ctrl-Z shortcuts respectively.
=> GUI: basic undo redo

src/main/java/axoloti/ObjectSearchFrame.java, src/main/java/axoloti/Patch.java, src/main/java/axoloti/PatchFrame.java, src/main/java/axoloti/Theme.java, src/main/java/axoloti/dialogs/ThemeEditor.java, src/main/java/axoloti/object/AxoObjectInstance.java
Both object replace and edit were resulting in multiple undo steps as well. This patch makes sure that they're squashed down as well as in the original promotion case: 
1. undoing a promotion connection removes the connection and returns the object to its unpromoted state
2. undoing a replace does the expected thing
3. object editing is kept out of the patch edit history, previously this would cause useless undo states to accumulate. I think what we probably want eventually is undo and redo for the object editor itself.
This also fixes an issue with the keyboard shortcuts that was caused by the menu enabled state not being updated.
=> GUI: fix undo for promotion and replace

src/main/java/axoloti/object/AxoObjectInstanceAbstract.java, src/main/java/axoloti/object/AxoObjectInstanceComment.java, src/main/java/axoloti/object/AxoObjectInstanceHyperlink.java
Dragging comments was buggy due to some unnecessarily duplicated event handling code that wasn't handling zooming properly. Also, selection and manipulation for both comments and hyperlinks was a bit unresponsive. The strut on the left part of the comment created an event dead zone. This patch makes these interactions a bit more forgiving.
=> GUI: cleanup comment and hyperlink event handling

src/main/java/axoloti/object/AxoObject.java, src/main/java/axoloti/object/AxoObjectFromPatch.java, src/main/java/axoloti/object/AxoObjectInstance.java, src/main/java/axoloti/objecteditor/AxoObjectEditor.java
This pull request causes the object editor to persist its bounds and active tab. This came up as an annoyance on the forums.
There is a bit of trickiness involved for the patcher object case because these data have to be stored on the instance rather than the object type due to the fact that the patcher recreates an AxoObject (the type) whenever updateObj occurs. There is a small change that makes "Revert" behave similarly.
=> GUI: persist bounds and active tab of object editor

src/main/java/axoloti/MainFrame.java, src/main/java/axoloti/Net.java, src/main/java/axoloti/NetDragging.java, src/main/java/axoloti/ObjectSearchFrame.java, src/main/java/axoloti/Patch.java, src/main/java/axoloti/PatchFrame.java, src/main/java/axoloti/PatchGUI.java, src/main/java/axoloti/ZoomUI.java, src/main/java/axoloti/ZoomUtils.java, src/main/java/axoloti/dialogs/PreferencesFrame.java, src/main/java/axoloti/iolet/IoletAbstract.java, src/main/java/axoloti/object/AxoObjectInstanceAbstract.java, src/main/java/axoloti/object/AxoObjectInstanceComment.java, src/main/java/axoloti/object/AxoObjectInstanceHyperlink.java, src/main/java/axoloti/object/AxoObjectInstanceZombie.java, src/main/java/axoloti/utils/Constants.java, src/main/java/axoloti/utils/LRUCache.java, src/main/java/components/DropDownComponent.java
This PR improves the responsiveness of the patch ui by:
- avoiding unnecessary repaints
- trying to only paint regions of the canvas that actually need to be repainted
- changing the net rendering code such that nets are drawn relative to their own bounds rather than to the size of the patch (this was resulting in many unnecessary net repaint calls because all nets overlapped even when drawing on nonoverlapping regions)
=> GUI: patch rendering performance improvements

src/main/java/axoloti/Net.java, src/main/java/axoloti/iolet/IoletAbstract.java
This PR eliminates the annoying problem of highlighted cables during robot drags. Also, we avoid repainting a net if its highlight state hasn't actually changed.
=> GUI: avoid cable highlight during robot drag

src/main/java/axoloti/PatchFrame.form, src/main/java/axoloti/PatchFrame.java
Fix zoom and undo such that on Mac we use Command rather than Control. Also, add a CMD/Ctrl-0 shortcut to return to default zoom.
=> GUI: cross platform keyboard shortcuts

src/main/java/axoloti/PatchGUI.java, src/main/java/axoloti/ZoomUI.java
With Mark's latest commit, we've moved to a single modifier, ALT, to control zooming and panning. It is used in two ways: either to 1. allow zooming from mouse wheel events (from the trackpad or from a real mouse wheel) or 2. to allow smooth panning with a single finger drag or mouse motion. Without ALT, the trackpad has the default mouse wheel behavior.
This patch fixes two things:
1. We ensure that the drag cursor is only shown once a drag has actually started, not just when ALT is pressed.
2. Previously the ALT behavior wasn't handled correctly when a UI component implementing KeyListener was focused (DialComponent for example). We now route this event to the correct handler in the main JLayeredPane, so ALT panning works as expected everywhere in the canvas.
=> GUI: clean up alt modifier panning

src/main/java/axoloti/MainFrame.form, src/main/java/axoloti/MainFrame.java, src/main/java/axoloti/PatchFrame.form, src/main/java/axoloti/PatchFrame.java, src/main/java/axoloti/PatchGUI.java, src/main/java/axoloti/ZoomUI.java, src/main/java/axoloti/menus/FileMenu.java, src/main/java/axoloti/menus/WindowMenu.java, src/main/java/axoloti/utils/KeyUtils.java, src/main/java/components/control/ACtrlComponent.java, src/main/java/components/control/Checkbox4StatesComponent.java, src/main/java/components/control/CheckboxComponent.java, src/main/java/components/control/DialComponent.java, src/main/java/components/control/HRadioComponent.java, src/main/java/components/control/NumberBoxComponent.java, src/main/java/components/control/VRadioComponent.java
This patch replaces ALT with CTRL/CMD for our standard modifier. I also took the opportunity to clean up some of our key handling code so future changes like this are easier to make.
=> GUI: standardize on control or cmd modifier

src/main/java/axoloti/iolet/IoletAbstract.java
Previously, the jack drop target for both inlets and outlets extended out to the right of the jack. The patch compacts the target so that it is flush with the jack itself.
We also try to be more careful to avoid null pointer exceptions when setting the highlight state.
=> GUI: make drop target flush with jack, fix NPE

src/main/java/axoloti/Net.java, src/main/java/axoloti/NetDragging.java, src/main/java/axoloti/Patch.java, src/main/java/axoloti/PatchGUI.java, src/main/java/axoloti/displays/DisplayInstance1.java, src/main/java/axoloti/iolet/IoletAbstract.java, src/main/java/axoloti/object/AxoObjectInstanceAbstract.java, src/main/java/axoloti/parameters/ParameterInstance.java, src/main/java/axoloti/parameters/ParameterInstanceFrac32UMap.java, src/main/java/components/control/DialComponent.java
Fixes for:
- inaccurate net repaint on undo/redo
- some disp components not repainting in live mode
- not repainting objects properly after a midi cc / preset / modulation selection from the context menu
- dial components not repainting on keyboard change specifically at default zoom
I verified that repaints happen normally when a parameter is controlled from an external midi controller.
=> GUI: various repaint fixes

src/main/java/axoloti/Patch.java, src/main/java/axoloti/ZoomUI.java, src/main/java/components/AssignPresetPanel.java
These changes solve the preset panel repaint interaction issue and ensure that the components there are shown at the patch zoom level.
=> GUI: zoomed preset panel components

src/main/java/axoloti/Net.java, src/main/java/axoloti/PatchGUI.java, src/main/java/axoloti/ZoomRepaintManager.java, src/main/java/axoloti/ZoomUI.java, src/main/java/axoloti/ZoomUtils.java, src/main/java/axoloti/attribute/AttributeInstanceObjRef.java, src/main/java/axoloti/attribute/AttributeInstanceSDFile.java, src/main/java/axoloti/attribute/AttributeInstanceTablename.java, src/main/java/axoloti/attribute/AttributeInstanceWavefile.java, src/main/java/axoloti/displays/DisplayInstance1.java, src/main/java/axoloti/object/AxoObjectInstanceAbstract.java, src/main/java/axoloti/object/AxoObjectInstanceComment.java, src/main/java/axoloti/object/AxoObjectInstanceZombie.java, src/main/java/axoloti/parameters/ParameterInstance.java, src/main/java/axoloti/parameters/ParameterInstanceFrac32UMap.java, src/main/java/components/DropDownComponent.java, src/main/java/components/VGraphComponent.java, src/main/java/components/control/ACtrlComponent.java, src/main/java/components/control/Checkbox4StatesComponent.java, src/main/java/components/control/CheckboxComponent.java, src/main/java/components/control/DialComponent.java, src/main/java/components/control/NumberBoxComponent.java, src/main/java/components/control/VSliderComponent.java
The fundamental problem with our current zooming approach is that the components themselves are unaware of the fact that they're in a layer context that might apply a scale factor. So a call to repaint() from inside a component results in the unscaled region being repainted, not the entire zoomed region in the containing layer.
This patch uses a custom RepaintManager in such a way that standard repaints end up setting the appropriate zoomed region as dirty and swing takes care of the rest. Painting is completely removed from ZoomUI aside from the one place where we perform the scaling of a layer. We also return to our repaint strategy from before zoom was originally merged where each component is responsible for calling repaint in the appropriate place.
=> GUI: fix zoom and repaint strategy

src/main/java/components/AssignPresetMenuItems.java
Noticed this bug in master when developing something on one of my feature branches.
Current behavior:
- Select "Clear all presets" from the preset assign menu without first "Including in current preset" -> NPE
or
- Include and then exclude a parameter, then clear all. -> NPE
It's annoying to check for and then reassign null when dealing with fields that may be persisted. It would be nice to come up with a better strategy for default values for these fields. Going to give that some thought, but for now here's the easy fix.
=> GUI: fix preset clear null pointer exception

src/main/java/axoloti/Net.java, src/main/java/axoloti/Patch.java, src/main/java/axoloti/parameters/ParameterInstanceFrac32UMap.java, src/main/java/axoloti/realunits/DecayTime.java, src/main/java/axoloti/realunits/DecayTimeReverse.java, src/main/java/axoloti/realunits/FilterQ.java, src/main/java/axoloti/realunits/FreqHz.java, src/main/java/axoloti/realunits/KPitchHz.java, src/main/java/axoloti/realunits/LFOBPM.java, src/main/java/axoloti/realunits/LFOPeriod.java, src/main/java/axoloti/realunits/LFOPitchHz.java, src/main/java/axoloti/realunits/LFORatio.java, src/main/java/axoloti/realunits/LinDB.java, src/main/java/axoloti/realunits/LinRatio.java, src/main/java/axoloti/realunits/LinearTimeExp.java, src/main/java/axoloti/realunits/LinearTimeReverse.java, src/main/java/axoloti/realunits/NativeToReal.java, src/main/java/axoloti/realunits/PitchHz.java, src/main/java/axoloti/realunits/PitchToNote.java, src/main/java/axoloti/realunits/PitchToRatio.java, src/main/java/axoloti/realunits/SquareDB.java, src/main/java/axoloti/realunits/SquareRatio.java, src/main/java/components/control/DialComponent.java
Hi,
These patches allow modifiers to be used when typing values into dials, e.g. 'x' for ratios, 'h' for frequencies, 's' for periods, 'd' for decibels, '/' for bpms. 'k'ilo and 'm'illi prefixes are supported, and extraneous spaces and letters should be silently eaten. I've tried to make it as "do what I mean" as I could without making it contradictory, ambiguous, or unpredictable.
I'm sure there'll be room for improvement, but I thought I'd get this out there.
Lisa
=> Keyed-in unit interpretation

platform_osx/build.sh
this branch needs 7z, master branch used unzip, so chances are people don't have it yet
=> check for needed executables (7z in this case)

src/main/java/axoloti/abstractui/DocumentWindowList.java, src/main/java/axoloti/swingui/MainFrame.java
Previously MainFrame never unregistered itself, so DocumentWindowList was non-empty forever hanging the app on close.
=> Fix MainFrame close infinite loop

src/main/java/axoloti/swingui/patch/object/AxoObjectInstanceViewAbstract.java
Currently, if you click on one object to select it (rather than drawing a selection bounding box), it grabs focus and then subsequent key operation events like deletion and arrow key movement have no effect because they don't reach the handler attached to Layers. If we keep the focus on Layers, then a selected-by-click object acts exactly like bounding box select objects.
=> Fix single selected object deletion

src/main/java/axoloti/swingui/patch/object/attribute/AttributeInstanceViewObjRef.java, src/main/java/axoloti/swingui/patch/object/attribute/AttributeInstanceViewSDFile.java, src/main/java/axoloti/swingui/patch/object/attribute/AttributeInstanceViewTablename.java
The document associated with a textfield is modified recursively and an exception is thrown if edited when there are multiple views of it open. setModelUndoableProperty triggers a model event that ultimately causes a string to be compared to the current textfield text which has already changed by the time the comparison occurs. Calling setModelUndoableProperty inside an invokeLater defers this comparison and all copies of the textfield track the edit as we expect.
=> Fix tricky textfield recursive edit bug

src/main/java/axoloti/object/AxoObject.java, src/main/java/axoloti/object/AxoObjectAbstract0.java, src/main/java/axoloti/object/AxoObjectFromPatch.java, src/main/java/axoloti/object/IAxoObject.java, src/main/java/axoloti/patch/object/AxoObjectInstance.java, src/main/java/axoloti/piccolo/objectviews/PAxoObjectInstanceView.java, src/main/java/axoloti/swingui/objecteditor/AxoObjectEditor.java, src/main/java/axoloti/swingui/patch/object/AxoObjectInstanceView.java, src/main/java/axoloti/swingui/patch/object/AxoObjectInstanceViewPatcherObject.java
Currently, in experimental, selecting "edit object definition" from the object menu does nothing. The editor frame is created, but remains invisible. This PR re-enables it and simplifies persistence of its bounds and active-tab state. The editor itself will need further verification as we continue development on this branch.
=> Re-enable object editor

src/main/java/axoloti/swingui/patch/PatchFrame.java
If a new view is created of a patch view that is already live, we explicitly unlock it, so the patch is still live, but all views of it are unlocked. This change makes the new view respect the lock state of the patch when it is created (ShowConnect is called during PatchFrame creation if the connection is connected). It doesn't seem like there is a case where ShowConnect will be called, and we would want to explicitly unlock a locked patch.
=> Fix 'new view' live state

src/main/java/axoloti/abstractui/PatchView.java
There are a couple of undo bugs in 'experimental' right now:
1. A patch is considered dirty immediately after launch, so the user is prompted to save on close even if no edits have occurred.
2. By repeatedly undoing after making some edits, it is possible to go beyond the initial state the patch had when it was opened. Visually this looks like everything is removed from the patch view.
This is happening because UndoableEdits accumulate in the UndoManager when a patch is opened; setModelUndoableProperty is called repeatedly during the initialization process. One simple way to fix this is to discard these edits just before a PatchFrame is created. The dirty state works as we expect with this change: 1. A patch is clean immediately after being opened. 2. Undoing all the edits back to the …
=> Fix initial undo/dirty state

platform_linux/build.sh
The key change is at line 104. There was a dash instead of an underscore in the archive path causing the build to fail. "./fatfs-0.13-patched.7z" should be "fatfs-0.13_patched.7z." The rest is just automated trailing whitespace removal.
=> Fix linux build.sh typo

Axoloti.bat, Axoloti.sh
The launch scripts were still pointing to 0.8.2, so launching the patcher via Axoloti.sh was silently not loading Marlin. We still had the problematic sun-java2d jar there as well.
=> Update launch script jvmargs for latest Marlin

src/main/java/axoloti/swingui/MainFrame.java
Background: Previously threw with JDK10, now works as expected.
=> GUI: fix log (use document length instead of offset)

platform_linux/build.sh
Couple of small changes/fixed to make the `platform_linux/build.sh` script work again, tested using a `ubuntu:18.04` container.
Tbh I don't think this script should install udev rules, but since I didn't want to introduce any unrelated changes for a simple fix I added `udev` to the list of packages to install otherwise the `/etc/udev/rules.d` directory doesn't exist and `udevadm` is missing.
Fixes #433
=> Fix linux build on experimental branch

.travis.yml
Closes #443 
Travis was using openjdk 11 for linux and java 10 for osx, ignoring whatever was custom installed by the script. The [docs](https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks) suggest using the `jdk` keyword, but:
- oraclejdk8 is no longer preinstalled in the default linux distribution (xenial). https://github.com/travis-ci/travis-ci/issues/10290 recommends using "trusty" or moving to openjdk.
- Something similar was happening on osx for xcode8.2 (which is not even shown in the [docs](https://docs.travis-ci.com/user/reference/osx/#jdk-and-macos)).
=> Fix travis builds / ensure oraclejdk8
